version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: at-erp
    environment:
      POSTGRES_DB: at-erp
      POSTGRES_USER: at-admin
      POSTGRES_PASSWORD: admin-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  db_init:
    image: postgres:latest
    depends_on:
      - postgres
    environment:
      PGPASSWORD: admin-password
    entrypoint: >
      bash -c "
        sleep 10;
        psql -h postgres -U at-admin -d at-erp -c \"CREATE USER limited_user WITH PASSWORD '1234';\";
        psql -h postgres -U at-admin -d at-erp -c \"GRANT CONNECT ON DATABASE at-erp TO limited_user;\";
        psql -h postgres -U at-admin -d at-erp -c \"GRANT USAGE ON SCHEMA public TO limited_user;\";
        psql -h postgres -U at-admin -d at-erp -c \"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO limited_user;\";
        psql -h postgres -U at-admin -d at-erp -c \"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO limited_user;\";
      "
#      разграничение доступа к бд

    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge